### ISSUE TITLE
Display realtime COTS detections on the desktop app

### ISSUE THREAD

**Issue by gcoleman72** [open-AIMS/reefscan_desktop_data_manager#10]
As a COTS controller I want to see on a computer screen where the COTS are so that I can control them.

Add a TAB on the "Data Page" caller "Real time COTS detections". This should be available be available for Sequences that are downloaded but also for sequences that have not yet been downloaded.

Show a list of COTS detections

In the same eay that the application copies the survey.json file before all of the data is downloaded, it should also read the COTS file

**Comment by gcoleman72** [comment]
The table should be generated from the sequence detection file and should include
    sequence_id
    class_id and maximum_score (for the class with the highest maximum score)

**Comment by gcoleman72** [comment]
JSON files are in the same folder as the photos

**Comment by bmarsh-aims** [comment]
Attaching word doc that describes json files for different detection types.

[explanation of json describing different cots detections.docx](https://github.com/open-AIMS/reefscan_desktop_data_manager/files/12745729/explanation.of.json.describing.different.cots.detections.docx)
