### ISSUE TITLE
Display end-of-day COTS detections on the desktop app

### ISSUE THREAD

**Issue by gcoleman72** [open-AIMS/reefscan_desktop_data_manager#11]
As a COTS controller I want to see on a computer screen where the COTS are so that I can control them.

Add a TAB on the "Data Page" caller "End-of-day time COTS detections". This should be available be available for Sequences that are downloaded

Show a list of COTS detections

**Comment by gcoleman72** [comment]
Table should include filename and number of detections. Ignore files with zero detections.

**Comment by bmarsh-aims** [comment]
Attaching word doc describing all json detection file types.

[explanation of json describing different cots detections.docx](https://github.com/open-AIMS/reefscan_desktop_data_manager/files/12745725/explanation.of.json.describing.different.cots.detections.docx)
